version: "3"
services:
  el:
    image: nethermind/nethermind
    network_mode: host
    command: >
      --config config
      --Init.ChainSpecPath ./configs/spec.json
      --JsonRpc.JwtSecretFile /shared/jwtsecret
      --Merge.TerminalTotalDifficulty 3402823669209384634633746074317682114540
    # TTD 0x9ffffffffffffffffffffffffffffffec = 10 * 0xfffffffffffffffffffffffffffffffe = 3402823669209384634633746074317682114540
    # TTD 0x63ffffffffffffffffffffffffffffff38 = 100 * 0xfffffffffffffffffffffffffffffffe = 34028236692093846346337460743176821145400
    volumes:
      - "./shared:/shared"
      - "./nethermind:/nethermind/configs"

  cl:
    image: chainsafe/lodestar:next
    network_mode: host
    command: >
      dev
      --genesisValidators 32
      --startValidators 0..31
      --api.rest.enabled
      --api.rest.host 0.0.0.0
      --logFile beacon.log
      --logLevelFile debug
      --logRotate
      --logMaxFiles 5
      --sync.isSingleNode
      --eth1.enabled=true
      --eth1.providerUrls http://127.0.0.1:8545
      --execution.urls http://127.0.0.1:8551
      --jwt-secret /shared/jwtsecret
      --params.ALTAIR_FORK_EPOCH 0
      --params.BELLATRIX_FORK_EPOCH 1
      --terminal-total-difficulty-override 3402823669209384634633746074317682114540
    volumes:
      - "./shared:/shared"
